import React, { useState, useEffect } from 'react';
import { Wifi, Cpu, ShieldAlert, CheckCircle2, Server, Radio, Send, Play, Square, RefreshCw, MessageSquare } from 'lucide-react';
import { PROTOCOL_GATEWAYS, DATA_SOURCES } from '../config/equipmentTypes';
import api from '../services/api';

export const DeviceConnections = ({ machines = [], telemetry = [] }) => {
  const [telegramStatus, setTelegramStatus] = useState(null);
  const [testSending, setTestSending] = useState(false);
  const [testResult, setTestResult] = useState(null);
  const [simStatus, setSimStatus] = useState(null);

  useEffect(() => {
    fetchStatus();
  }, []);

  const fetchStatus = async () => {
    try {
      const [tRes, sRes] = await Promise.all([
        api.getTelegramStatus().catch(() => null),
        api.getSimulatorStatus().catch(() => null),
      ]);
      if (tRes) setTelegramStatus(tRes);
      if (sRes) setSimStatus(sRes);
    } catch (err) {
      console.error("Failed to fetch connection statuses:", err);
    }
  };

  const handleTestTelegram = async () => {
    setTestSending(true);
    setTestResult(null);
    try {
      const res = await api.testTelegramMessage();
      setTestResult({ success: true, message: res.message || 'Test message sent successfully!' });
    } catch (err) {
      setTestResult({ success: false, message: err.message || 'Failed to send test Telegram message.' });
    } finally {
      setTestSending(false);
    }
  };

  const handleToggleSim = async () => {
    try {
      if (simStatus?.is_running) {
        await api.stopSimulator();
      } else {
        await api.startSimulator();
      }
      fetchStatus();
    } catch (err) {
      console.error("Simulator toggle error:", err);
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.75rem' }}>
      {/* Physical Hardware Disclaimer Banner */}
      <div style={{
        backgroundColor: 'rgba(56, 189, 248, 0.08)',
        border: '1px solid rgba(56, 189, 248, 0.25)',
        borderRadius: 'var(--radius-lg)',
        padding: '1.25rem',
        display: 'flex',
        alignItems: 'center',
        gap: '1rem',
      }}>
        <div style={{
          backgroundColor: 'rgba(56, 189, 248, 0.15)',
          padding: '0.75rem',
          borderRadius: '50%',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
        }}>
          <Server size={24} color="var(--accent-cyan)" />
        </div>
        <div>
          <div style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--accent-cyan)', marginBottom: '0.25rem' }}>
            VIRTUAL MACHINE DIGITAL TWIN MODE ACTIVE
          </div>
          <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: 1.5 }}>
            No physical hardware sensors or machinery connected. All sensor signals, operating parameters, and ML failure predictions are generated by the software-based Digital Twin Telemetry Engine and persists to MongoDB Atlas.
          </div>
        </div>
      </div>

      {/* Simulator & Telegram Integration Connection Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '1.25rem' }}>
        {/* Virtual Device Simulator Card */}
        <div className="card" style={{ marginBottom: 0 }}>
          <div className="card-header">
            <div className="card-title">
              <Cpu size={20} color="var(--accent-cyan)" />
              <span>Virtual Machine Digital Twin Simulator</span>
            </div>
            <span className="source-tag" style={{
              backgroundColor: simStatus?.is_running ? 'rgba(16, 185, 129, 0.15)' : 'rgba(100, 116, 139, 0.15)',
              color: simStatus?.is_running ? 'var(--status-normal)' : 'var(--text-muted)'
            }}>
              {simStatus?.is_running ? 'RUNNING (LIVE)' : 'STOPPED / PAUSED'}
            </span>
          </div>

          <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '1rem', lineHeight: 1.5 }}>
            Generates real-time time-series telemetry across 7 equipment categories and 4 operational scenarios.
          </div>

          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1.25rem' }}>
            <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>
              Active Virtual Machines: <strong style={{ color: 'var(--text-primary)' }}>{simStatus?.machine_count || machines.length}</strong>
            </div>
            <button
              className={`btn ${simStatus?.is_running ? 'btn-outline' : 'btn-primary'}`}
              onClick={handleToggleSim}
              style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}
            >
              {simStatus?.is_running ? (
                <>
                  <Square size={14} color="#ef4444" />
                  <span>Pause Simulator</span>
                </>
              ) : (
                <>
                  <Play size={14} color="#10b981" />
                  <span>Start Live Simulator</span>
                </>
              )}
            </button>
          </div>
        </div>

        {/* Telegram Bot Connection Status Card */}
        <div className="card" style={{ marginBottom: 0 }}>
          <div className="card-header">
            <div className="card-title">
              <MessageSquare size={20} color="var(--accent-indigo)" />
              <span>Telegram Bot Notification Service</span>
            </div>
            <span className="source-tag" style={{
              backgroundColor: telegramStatus?.enabled && telegramStatus?.configured ? 'rgba(16, 185, 129, 0.15)' : 'rgba(239, 68, 68, 0.15)',
              color: telegramStatus?.enabled && telegramStatus?.configured ? 'var(--status-normal)' : 'var(--status-critical)'
            }}>
              {telegramStatus?.status_label || 'Checking...'}
            </span>
          </div>

          <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '1rem', lineHeight: 1.5 }}>
            Sends instant structured notifications for WARNING and CRITICAL machine faults using official Telegram Bot API.
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem', marginBottom: '1.25rem', fontSize: '0.82rem', fontFamily: 'var(--font-mono)' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ color: 'var(--text-muted)' }}>Chat ID:</span>
              <span style={{ color: 'var(--accent-cyan)' }}>{telegramStatus?.chat_id_redacted || 'Not Configured'}</span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ color: 'var(--text-muted)' }}>Alert Cooldown:</span>
              <span style={{ color: 'var(--text-primary)' }}>{telegramStatus?.cooldown_sec || 60}s per machine</span>
            </div>
          </div>

          <button
            className="btn btn-outline"
            onClick={handleTestTelegram}
            disabled={testSending}
            style={{ width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}
          >
            <Send size={14} />
            <span>{testSending ? 'Sending Test Alert...' : 'Send Test Telegram Alert'}</span>
          </button>

          {testResult && (
            <div style={{
              marginTop: '0.75rem',
              padding: '0.65rem 0.85rem',
              borderRadius: 'var(--radius-md)',
              fontSize: '0.8rem',
              backgroundColor: testResult.success ? 'rgba(16, 185, 129, 0.12)' : 'rgba(239, 68, 68, 0.12)',
              color: testResult.success ? 'var(--status-normal)' : 'var(--status-critical)',
              border: `1px solid ${testResult.success ? 'rgba(16, 185, 129, 0.3)' : 'rgba(239, 68, 68, 0.3)'}`,
            }}>
              {testResult.message}
            </div>
          )}
        </div>
      </div>

      {/* Protocol Gateway Readiness Cards */}
      <div className="card" style={{ marginBottom: 0 }}>
        <div className="card-header">
          <div className="card-title">
            <Wifi size={20} color="var(--accent-cyan)" />
            <span>Industrial Fieldbus & IoT Gateway Connectors</span>
          </div>
          <span className="source-tag live">
            INTEGRATION READY
          </span>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '1.25rem' }}>
          {PROTOCOL_GATEWAYS.map((gw) => (
            <div
              key={gw.id}
              style={{
                backgroundColor: 'var(--bg-dark)',
                border: '1px solid var(--border-color)',
                borderRadius: 'var(--radius-lg)',
                padding: '1.25rem',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.65rem' }}>
                <div style={{ fontSize: '0.95rem', fontWeight: 700, color: 'var(--text-primary)' }}>{gw.name}</div>
                <Server size={18} color="var(--accent-cyan)" />
              </div>
              <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginBottom: '0.75rem' }}>
                Protocol: {gw.protocol}
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.78rem', color: 'var(--status-normal)', fontWeight: 600 }}>
                <CheckCircle2 size={14} />
                <span>{gw.status}</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Connected Equipment Devices Table */}
      <div className="card">
        <div className="card-header">
          <div className="card-title">
            <Cpu size={20} color="var(--accent-indigo)" />
            <span>Registered Virtual Equipment Devices</span>
          </div>
        </div>

        <div className="table-container">
          <table className="data-table">
            <thead>
              <tr>
                <th>Machine ID</th>
                <th>Equipment Type</th>
                <th>Data Source Mode</th>
                <th>Connection Status</th>
                <th>Last Active Telemetry</th>
                <th>Hardware Protocol</th>
              </tr>
            </thead>
            <tbody>
              {machines.map((m) => {
                const latest = telemetry.find((t) => t.machine_id === m.machine_id);
                const isSimulated = true;
                const source = DATA_SOURCES.SIMULATED;

                return (
                  <tr key={m.machine_id}>
                    <td style={{ fontFamily: 'var(--font-mono)', fontWeight: 700 }}>{m.machine_id}</td>
                    <td>{m.machine_type === 'CNC' ? 'CNC Mill / Motor' : '3D Printer / Fan'}</td>
                    <td>
                      <span className="source-tag" style={{ backgroundColor: source.bg, color: source.color }}>
                        {source.label}
                      </span>
                    </td>
                    <td>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', color: latest ? 'var(--status-normal)' : 'var(--text-muted)', fontWeight: 600 }}>
                        <Radio size={12} color={latest ? 'var(--status-normal)' : 'var(--text-muted)'} />
                        <span>{latest ? 'Online (Streaming)' : 'Awaiting Signals'}</span>
                      </div>
                    </td>
                    <td style={{ fontSize: '0.82rem', color: 'var(--text-secondary)' }}>
                      {latest ? new Date(latest.timestamp).toLocaleString() : 'No readings ingested'}
                    </td>
                    <td style={{ fontFamily: 'var(--font-mono)', fontSize: '0.8rem', color: 'var(--accent-cyan)' }}>
                      Virtual Digital Twin / REST
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default DeviceConnections;
